### ISSUE TITLE
Live reloading with hugo server doesn't work

### ISSUE THREAD

**Issue by Lesstat** [janraasch/hugo-scroll#31]
Hi,

I just started experimenting with hugo-scroll and copied the example site. If I change anything on the site while `hugo server` is running, I end up with just the title, an empty menu and no sections. If I stop `hugo server` and restarted again the page looks fine including my changes.

Any idea what is going wrong here (maybe I am doing it wrong...)

Best regards
Lesstat

**Comment by janraasch** [comment]
Hi @Lesstat, does the issue still persist?

> Any idea what is going wrong here (maybe I am doing it wrong...)

It is hard to tell from afar 😁.

## context

* Is your source code somewhere on GitHub or otherwise publicly available, so I could check it out to see, if I can reproduce the problem?
* Did you get some JavaScript or Network Errors on the browser you are using? Which browser are you using by the way? Do other browsers have the same issue?
* Which version of Hugo are you using & what operating system are you working with?

Thank you & kind regards 👋🏻,
Jan
